server:
  port: 7002

spring: 
  cloud:
    config:
      discovery:
        serviceId: configserver
        enabled: true 

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

spring:
  profiles: 
    dev:
      datasource:
        url: jdbc:mysql://localhost/customer
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
      
      jpa:
        hibernate:
         ddl-auto: create-update
         show-sql: true
  
  
