spring:
  profiles: prod

server:
  port: 9999

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

spring.datasource:
    url: jdbc:mysql://localhost/customer
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

spring.jpa:
    hibernate:
      ddl-auto: create-update
    show-sql: true



  
